# .scrutinizer.yml
filter:
  excluded_paths: [tests/*]

build:
  environment:
    php:
      version: 5.6.9

checks:
    php:
        code_rating: true
        duplication: true

tools:
  external_code_coverage:
    timeout: 600
