# .scrutinizer.yml
filter:
    excluded_paths:
        - tests/*

build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=/tmp/coverage.xml'
                coverage:
                    file: '/tmp/coverage.xml'
                    format: 'php-clover'
